// AUTO-GENERATED by scripts/buildCatalog.mjs — do not edit by hand.
// Source: "Group 4 - GardenGuard Data Plus" (18 region JSON files).
// Regenerate with: node scripts/buildCatalog.mjs
//
// Stats: 123 plants · 35 pests · 15 companion remedies
// (510 raw entries across 18 files).

import type { CatalogPlant } from '../models/types';

export const CATALOG: CatalogPlant[] = [
  {
    "id": "ageratum",
    "name": "Ageratum",
    "category": "flower",
    "regions": [
      "northeast",
      "northwest",
      "southwest"
    ],
    "pests": [
      "whiteflies"
    ]
  },
  {
    "id": "anise-hyssop",
    "name": "Anise Hyssop",
    "category": "herb",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": []
  },
  {
    "id": "aster",
    "name": "Aster",
    "category": "flower",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "astilbe",
    "name": "Astilbe",
    "category": "flower",
    "regions": [
      "north_central",
      "northeast",
      "northwest"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "azalea",
    "name": "Azalea",
    "category": "flower",
    "regions": [
      "southeast"
    ],
    "pests": [
      "lace-bugs"
    ]
  },
  {
    "id": "basil",
    "name": "Basil",
    "category": "herb",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "aphids",
      "japanese-beetles",
      "spider-mites"
    ]
  },
  {
    "id": "bee-balm",
    "name": "Bee Balm (Monarda)",
    "category": "flower",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "powdery-mildew"
    ]
  },
  {
    "id": "beet",
    "name": "Beet",
    "category": "vegetable",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "leaf-miners"
    ]
  },
  {
    "id": "begonia",
    "name": "Begonia",
    "category": "flower",
    "regions": [
      "southeast"
    ],
    "pests": [
      "whiteflies"
    ]
  },
  {
    "id": "bell-pepper",
    "name": "Bell Pepper",
    "category": "vegetable",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "aphids",
      "spider-mites",
      "whiteflies"
    ]
  },
  {
    "id": "black-eyed-susan",
    "name": "Black-Eyed Susan",
    "category": "flower",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "blackfoot-daisy",
    "name": "Blackfoot Daisy",
    "category": "flower",
    "regions": [
      "southwest"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "blanket-flower",
    "name": "Blanket Flower (Gaillardia)",
    "category": "flower",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southwest"
    ],
    "pests": [
      "leafhoppers"
    ]
  },
  {
    "id": "bleeding-heart",
    "name": "Bleeding Heart",
    "category": "flower",
    "regions": [
      "north_central",
      "northeast",
      "northwest"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "blue-daze",
    "name": "Blue Daze (Evolvulus)",
    "category": "flower",
    "regions": [
      "southeast"
    ],
    "pests": [
      "whiteflies"
    ]
  },
  {
    "id": "blue-flax",
    "name": "Blue Flax",
    "category": "flower",
    "regions": [
      "southwest"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "bluebonnet",
    "name": "Bluebonnet",
    "category": "flower",
    "regions": [
      "south_central"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "borage",
    "name": "Borage",
    "category": "herb",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": []
  },
  {
    "id": "broccoli",
    "name": "Broccoli",
    "category": "vegetable",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "cabbage-worms"
    ]
  },
  {
    "id": "brussels-sprouts",
    "name": "Brussels Sprouts",
    "category": "vegetable",
    "regions": [
      "north_central",
      "northeast",
      "northwest"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "cabbage",
    "name": "Cabbage",
    "category": "vegetable",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "aphids",
      "cabbage-loopers",
      "harlequin-bugs"
    ]
  },
  {
    "id": "caladium",
    "name": "Caladium",
    "category": "flower",
    "regions": [
      "southeast"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "camellia",
    "name": "Camellia",
    "category": "flower",
    "regions": [
      "southeast"
    ],
    "pests": [
      "tea-scale"
    ]
  },
  {
    "id": "campanula",
    "name": "Campanula",
    "category": "flower",
    "regions": [
      "north_central",
      "northeast",
      "northwest"
    ],
    "pests": [
      "slugs"
    ]
  },
  {
    "id": "canna-lily",
    "name": "Canna Lily",
    "category": "flower",
    "regions": [
      "southeast"
    ],
    "pests": [
      "leafrollers"
    ]
  },
  {
    "id": "carrot",
    "name": "Carrot",
    "category": "vegetable",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "carrot-rust-fly"
    ]
  },
  {
    "id": "catnip",
    "name": "Catnip",
    "category": "herb",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": []
  },
  {
    "id": "cauliflower",
    "name": "Cauliflower",
    "category": "vegetable",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "cabbage-loopers"
    ]
  },
  {
    "id": "celery",
    "name": "Celery",
    "category": "vegetable",
    "regions": [
      "north_central",
      "northeast",
      "northwest"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "chamomile",
    "name": "Chamomile",
    "category": "herb",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "chives",
    "name": "Chives",
    "category": "herb",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": []
  },
  {
    "id": "cilantro",
    "name": "Cilantro",
    "category": "herb",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "collard-greens",
    "name": "Collard Greens",
    "category": "vegetable",
    "regions": [
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "cabbage-worms",
      "harlequin-bugs"
    ]
  },
  {
    "id": "columbine",
    "name": "Columbine",
    "category": "flower",
    "regions": [
      "north_central",
      "northeast",
      "northwest"
    ],
    "pests": [
      "leaf-miners"
    ]
  },
  {
    "id": "coneflower",
    "name": "Coneflower (Echinacea)",
    "category": "flower",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast"
    ],
    "pests": [
      "japanese-beetles"
    ]
  },
  {
    "id": "coreopsis",
    "name": "Coreopsis",
    "category": "flower",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "cosmos",
    "name": "Cosmos",
    "category": "flower",
    "regions": [
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "cucumber",
    "name": "Cucumber",
    "category": "vegetable",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "aphids",
      "cucumber-beetles",
      "powdery-mildew"
    ]
  },
  {
    "id": "dahlia",
    "name": "Dahlia",
    "category": "flower",
    "regions": [
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "aphids",
      "spider-mites"
    ]
  },
  {
    "id": "daylily",
    "name": "Daylily",
    "category": "flower",
    "regions": [
      "north_central",
      "south_central"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "delphinium",
    "name": "Delphinium",
    "category": "flower",
    "regions": [
      "north_central",
      "northeast",
      "northwest"
    ],
    "pests": [
      "slugs"
    ]
  },
  {
    "id": "desert-globe-amaranth",
    "name": "Desert Globe Amaranth",
    "category": "flower",
    "regions": [
      "southwest"
    ],
    "pests": [
      "spider-mites"
    ]
  },
  {
    "id": "desert-marigold",
    "name": "Desert Marigold",
    "category": "flower",
    "regions": [
      "southwest"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "desert-willow",
    "name": "Desert Willow",
    "category": "flower",
    "regions": [
      "southwest"
    ],
    "pests": [
      "caterpillars"
    ]
  },
  {
    "id": "desert-zinnia",
    "name": "Desert Zinnia",
    "category": "flower",
    "regions": [
      "southwest"
    ],
    "pests": [
      "leafhoppers"
    ]
  },
  {
    "id": "dill",
    "name": "Dill",
    "category": "herb",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": []
  },
  {
    "id": "eggplant",
    "name": "Eggplant",
    "category": "vegetable",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "flea-beetles",
      "spider-mites"
    ]
  },
  {
    "id": "fennel",
    "name": "Fennel",
    "category": "herb",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "firecracker-penstemon",
    "name": "Firecracker Penstemon",
    "category": "flower",
    "regions": [
      "southwest"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "foxglove",
    "name": "Foxglove",
    "category": "flower",
    "regions": [
      "northwest"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "gardenia",
    "name": "Gardenia",
    "category": "flower",
    "regions": [
      "southeast"
    ],
    "pests": [
      "aphids",
      "whiteflies"
    ]
  },
  {
    "id": "garlic",
    "name": "Garlic",
    "category": "vegetable",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": []
  },
  {
    "id": "geranium",
    "name": "Geranium",
    "category": "flower",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "aphids",
      "whiteflies"
    ]
  },
  {
    "id": "globe-mallow",
    "name": "Globe Mallow",
    "category": "flower",
    "regions": [
      "southwest"
    ],
    "pests": [
      "spider-mites"
    ]
  },
  {
    "id": "green-beans",
    "name": "Green Beans",
    "category": "vegetable",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "mexican-bean-beetles"
    ]
  },
  {
    "id": "hellebore",
    "name": "Hellebore",
    "category": "flower",
    "regions": [
      "northwest"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "hibiscus",
    "name": "Hibiscus",
    "category": "flower",
    "regions": [
      "south_central",
      "southeast"
    ],
    "pests": [
      "aphids",
      "whiteflies"
    ]
  },
  {
    "id": "hollyhock",
    "name": "Hollyhock",
    "category": "flower",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southwest"
    ],
    "pests": [
      "japanese-beetles"
    ]
  },
  {
    "id": "hosta",
    "name": "Hosta",
    "category": "flower",
    "regions": [
      "north_central",
      "northeast",
      "northwest"
    ],
    "pests": [
      "slugs"
    ]
  },
  {
    "id": "hydrangea",
    "name": "Hydrangea",
    "category": "flower",
    "regions": [
      "southeast"
    ],
    "pests": [
      "aphids",
      "spider-mites"
    ]
  },
  {
    "id": "hyssop",
    "name": "Hyssop",
    "category": "herb",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": []
  },
  {
    "id": "impatiens",
    "name": "Impatiens",
    "category": "flower",
    "regions": [
      "southeast"
    ],
    "pests": [
      "thrips"
    ]
  },
  {
    "id": "iris",
    "name": "Iris",
    "category": "flower",
    "regions": [
      "north_central",
      "northeast",
      "northwest"
    ],
    "pests": [
      "iris-borers"
    ]
  },
  {
    "id": "kale",
    "name": "Kale",
    "category": "vegetable",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "aphids",
      "cabbage-worms"
    ]
  },
  {
    "id": "lantana",
    "name": "Lantana",
    "category": "flower",
    "regions": [
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "whiteflies"
    ]
  },
  {
    "id": "lavender",
    "name": "Lavender",
    "category": "herb",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": []
  },
  {
    "id": "leek",
    "name": "Leek",
    "category": "vegetable",
    "regions": [
      "north_central",
      "northeast",
      "northwest"
    ],
    "pests": [
      "onion-maggots"
    ]
  },
  {
    "id": "lemon-balm",
    "name": "Lemon Balm",
    "category": "herb",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "lemon-verbena",
    "name": "Lemon Verbena",
    "category": "herb",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "spider-mites"
    ]
  },
  {
    "id": "lettuce",
    "name": "Lettuce",
    "category": "vegetable",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "aphids",
      "slugs"
    ]
  },
  {
    "id": "liatris",
    "name": "Liatris",
    "category": "flower",
    "regions": [
      "south_central"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "liriope",
    "name": "Liriope",
    "category": "flower",
    "regions": [
      "southeast"
    ],
    "pests": [
      "scale"
    ]
  },
  {
    "id": "lupine",
    "name": "Lupine",
    "category": "flower",
    "regions": [
      "north_central",
      "northeast",
      "northwest"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "marigold",
    "name": "Marigold",
    "category": "flower",
    "regions": [
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": []
  },
  {
    "id": "marjoram",
    "name": "Marjoram",
    "category": "herb",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": []
  },
  {
    "id": "mexican-evening-primrose",
    "name": "Mexican Evening Primrose",
    "category": "flower",
    "regions": [
      "southwest"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "mexican-hat",
    "name": "Mexican Hat (Ratibida)",
    "category": "flower",
    "regions": [
      "south_central",
      "southwest"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "mexican-petunia",
    "name": "Mexican Petunia (Ruellia)",
    "category": "flower",
    "regions": [
      "southeast"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "mexican-sunflower",
    "name": "Mexican Sunflower (Tithonia)",
    "category": "flower",
    "regions": [
      "south_central",
      "southwest"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "mint",
    "name": "Mint",
    "category": "herb",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "spider-mites"
    ]
  },
  {
    "id": "nasturtium",
    "name": "Nasturtium",
    "category": "flower",
    "regions": [
      "northeast",
      "northwest",
      "south_central",
      "southeast"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "okra",
    "name": "Okra",
    "category": "vegetable",
    "regions": [
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "aphids",
      "stink-bugs"
    ]
  },
  {
    "id": "onion",
    "name": "Onion",
    "category": "vegetable",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "onion-maggots"
    ]
  },
  {
    "id": "oregano",
    "name": "Oregano",
    "category": "herb",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": []
  },
  {
    "id": "parsley",
    "name": "Parsley",
    "category": "herb",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "armyworms"
    ]
  },
  {
    "id": "parsnip",
    "name": "Parsnip",
    "category": "vegetable",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "root-maggots"
    ]
  },
  {
    "id": "peas",
    "name": "Peas",
    "category": "vegetable",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "penstemon",
    "name": "Penstemon",
    "category": "flower",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southwest"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "peony",
    "name": "Peony",
    "category": "flower",
    "regions": [
      "north_central",
      "northeast",
      "northwest"
    ],
    "pests": [
      "thrips"
    ]
  },
  {
    "id": "petunia",
    "name": "Petunia",
    "category": "flower",
    "regions": [
      "south_central",
      "southeast"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "phlox",
    "name": "Phlox",
    "category": "flower",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast"
    ],
    "pests": [
      "spider-mites"
    ]
  },
  {
    "id": "potato",
    "name": "Potato",
    "category": "vegetable",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "colorado-potato-beetle",
      "early-blight",
      "late-blight"
    ]
  },
  {
    "id": "pumpkin",
    "name": "Pumpkin",
    "category": "vegetable",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "aphids",
      "squash-bugs",
      "vine-borers"
    ]
  },
  {
    "id": "radish",
    "name": "Radish",
    "category": "vegetable",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "flea-beetles"
    ]
  },
  {
    "id": "red-yucca",
    "name": "Red Yucca",
    "category": "flower",
    "regions": [
      "southwest"
    ],
    "pests": [
      "scale"
    ]
  },
  {
    "id": "rosemary",
    "name": "Rosemary",
    "category": "herb",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "rudbeckia",
    "name": "Rudbeckia",
    "category": "flower",
    "regions": [
      "north_central",
      "northeast",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "rutabaga",
    "name": "Rutabaga",
    "category": "vegetable",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "root-maggots"
    ]
  },
  {
    "id": "sage",
    "name": "Sage",
    "category": "herb",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "cabbage-moths"
    ]
  },
  {
    "id": "salvia",
    "name": "Salvia",
    "category": "flower",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast"
    ],
    "pests": [
      "spider-mites"
    ]
  },
  {
    "id": "salvia-greggii",
    "name": "Salvia Greggii",
    "category": "flower",
    "regions": [
      "south_central",
      "southwest"
    ],
    "pests": [
      "spider-mites"
    ]
  },
  {
    "id": "sedum",
    "name": "Sedum",
    "category": "flower",
    "regions": [
      "north_central",
      "northeast",
      "northwest"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "shasta-daisy",
    "name": "Shasta Daisy",
    "category": "flower",
    "regions": [
      "north_central",
      "northeast"
    ],
    "pests": [
      "leaf-miners"
    ]
  },
  {
    "id": "snapdragon",
    "name": "Snapdragon",
    "category": "flower",
    "regions": [
      "northeast",
      "northwest",
      "south_central",
      "southwest"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "spinach",
    "name": "Spinach",
    "category": "vegetable",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "leaf-miners"
    ]
  },
  {
    "id": "summer-savory",
    "name": "Summer Savory",
    "category": "herb",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": []
  },
  {
    "id": "sunflower",
    "name": "Sunflower",
    "category": "flower",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "sweet-corn",
    "name": "Sweet Corn",
    "category": "vegetable",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "corn-earworm"
    ]
  },
  {
    "id": "sweet-potato",
    "name": "Sweet Potato",
    "category": "vegetable",
    "regions": [
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "weevils"
    ]
  },
  {
    "id": "swiss-chard",
    "name": "Swiss Chard",
    "category": "vegetable",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "leaf-miners"
    ]
  },
  {
    "id": "tarragon",
    "name": "Tarragon",
    "category": "herb",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": []
  },
  {
    "id": "texas-bluebonnet",
    "name": "Texas Bluebonnet",
    "category": "flower",
    "regions": [
      "southwest"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "thyme",
    "name": "Thyme",
    "category": "herb",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": []
  },
  {
    "id": "tomato",
    "name": "Tomato",
    "category": "vegetable",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "aphids",
      "hornworms",
      "late-blight",
      "spider-mites",
      "whiteflies"
    ]
  },
  {
    "id": "turnip",
    "name": "Turnip",
    "category": "vegetable",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "root-maggots"
    ]
  },
  {
    "id": "verbena",
    "name": "Verbena",
    "category": "flower",
    "regions": [
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "spider-mites"
    ]
  },
  {
    "id": "veronica",
    "name": "Veronica",
    "category": "flower",
    "regions": [
      "north_central",
      "northeast",
      "northwest"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "winter-savory",
    "name": "Winter Savory",
    "category": "herb",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": []
  },
  {
    "id": "winter-squash",
    "name": "Winter Squash",
    "category": "vegetable",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "squash-bugs",
      "vine-borers"
    ]
  },
  {
    "id": "yarrow",
    "name": "Yarrow",
    "category": "flower",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "aphids"
    ]
  },
  {
    "id": "yellow-squash",
    "name": "Yellow Squash",
    "category": "vegetable",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "squash-bugs",
      "vine-borers"
    ]
  },
  {
    "id": "zinnia",
    "name": "Zinnia",
    "category": "flower",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "aphids",
      "spider-mites"
    ]
  },
  {
    "id": "zucchini",
    "name": "Zucchini",
    "category": "vegetable",
    "regions": [
      "north_central",
      "northeast",
      "northwest",
      "south_central",
      "southeast",
      "southwest"
    ],
    "pests": [
      "powdery-mildew",
      "squash-bugs",
      "vine-borers"
    ]
  }
];

/** Distinct pests in the dataset (raw labels; types/overrides live in pests.ts). */
export const DATASET_PESTS: { id: string; label: string }[] = [
  {
    "id": "aphids",
    "label": "Aphids"
  },
  {
    "id": "armyworms",
    "label": "Armyworms"
  },
  {
    "id": "cabbage-loopers",
    "label": "Cabbage Loopers"
  },
  {
    "id": "cabbage-moths",
    "label": "Cabbage Moths"
  },
  {
    "id": "cabbage-worms",
    "label": "Cabbage Worms"
  },
  {
    "id": "carrot-rust-fly",
    "label": "Carrot Rust Fly"
  },
  {
    "id": "caterpillars",
    "label": "Caterpillars"
  },
  {
    "id": "colorado-potato-beetle",
    "label": "Colorado Potato Beetle"
  },
  {
    "id": "corn-earworm",
    "label": "Corn Earworm"
  },
  {
    "id": "cucumber-beetles",
    "label": "Cucumber Beetles"
  },
  {
    "id": "early-blight",
    "label": "Early Blight"
  },
  {
    "id": "flea-beetles",
    "label": "Flea Beetles"
  },
  {
    "id": "harlequin-bugs",
    "label": "Harlequin Bugs"
  },
  {
    "id": "hornworms",
    "label": "Hornworms"
  },
  {
    "id": "iris-borers",
    "label": "Iris Borers"
  },
  {
    "id": "japanese-beetles",
    "label": "Japanese Beetles"
  },
  {
    "id": "lace-bugs",
    "label": "Lace Bugs"
  },
  {
    "id": "late-blight",
    "label": "Late Blight"
  },
  {
    "id": "leaf-miners",
    "label": "Leaf Miners"
  },
  {
    "id": "leafhoppers",
    "label": "Leafhoppers"
  },
  {
    "id": "leafrollers",
    "label": "Leafrollers"
  },
  {
    "id": "mexican-bean-beetles",
    "label": "Mexican Bean Beetles"
  },
  {
    "id": "onion-maggots",
    "label": "Onion Maggots"
  },
  {
    "id": "powdery-mildew",
    "label": "Powdery Mildew"
  },
  {
    "id": "root-maggots",
    "label": "Root Maggots"
  },
  {
    "id": "scale",
    "label": "Scale"
  },
  {
    "id": "slugs",
    "label": "Slugs"
  },
  {
    "id": "spider-mites",
    "label": "Spider Mites"
  },
  {
    "id": "squash-bugs",
    "label": "Squash Bugs"
  },
  {
    "id": "stink-bugs",
    "label": "Stink Bugs"
  },
  {
    "id": "tea-scale",
    "label": "Tea Scale"
  },
  {
    "id": "thrips",
    "label": "Thrips"
  },
  {
    "id": "vine-borers",
    "label": "Vine Borers"
  },
  {
    "id": "weevils",
    "label": "Weevils"
  },
  {
    "id": "whiteflies",
    "label": "Whiteflies"
  }
];

/** Global pest id -> companion-plant ids that repel it (the dataset's natural_remedies). */
export const PEST_REMEDIES: Record<string, string[]> = {
  "aphids": [
    "basil",
    "catnip",
    "chives",
    "garlic",
    "lavender",
    "marigold",
    "mint"
  ],
  "armyworms": [
    "mint",
    "rosemary"
  ],
  "cabbage-loopers": [
    "dill",
    "sage"
  ],
  "cabbage-moths": [
    "chamomile",
    "dill"
  ],
  "cabbage-worms": [
    "chamomile",
    "dill"
  ],
  "carrot-rust-fly": [
    "rosemary",
    "sage"
  ],
  "caterpillars": [
    "chamomile",
    "dill"
  ],
  "colorado-potato-beetle": [
    "catnip",
    "tansy"
  ],
  "corn-earworm": [
    "basil",
    "mint"
  ],
  "cucumber-beetles": [
    "nasturtium",
    "radish"
  ],
  "early-blight": [
    "chives",
    "garlic"
  ],
  "flea-beetles": [
    "catnip",
    "mint"
  ],
  "harlequin-bugs": [
    "garlic",
    "mint"
  ],
  "hornworms": [
    "borage",
    "dill"
  ],
  "iris-borers": [
    "chives",
    "garlic"
  ],
  "japanese-beetles": [
    "chives",
    "garlic"
  ],
  "lace-bugs": [
    "chives",
    "garlic"
  ],
  "late-blight": [
    "basil",
    "chives",
    "garlic"
  ],
  "leaf-miners": [
    "basil",
    "mint"
  ],
  "leafhoppers": [
    "basil",
    "mint"
  ],
  "leafrollers": [
    "chives",
    "garlic"
  ],
  "mexican-bean-beetles": [
    "marigold",
    "nasturtium"
  ],
  "onion-maggots": [
    "mint",
    "rosemary"
  ],
  "powdery-mildew": [
    "chives",
    "garlic"
  ],
  "root-maggots": [
    "mint",
    "rosemary"
  ],
  "scale": [
    "chives",
    "garlic"
  ],
  "slugs": [
    "mint",
    "rosemary"
  ],
  "spider-mites": [
    "basil",
    "chives",
    "lavender"
  ],
  "squash-bugs": [
    "nasturtium",
    "radish"
  ],
  "stink-bugs": [
    "garlic",
    "mint"
  ],
  "tea-scale": [
    "garlic",
    "mint"
  ],
  "thrips": [
    "basil",
    "lavender"
  ],
  "vine-borers": [
    "marigold",
    "mint"
  ],
  "weevils": [
    "marigold",
    "mint"
  ],
  "whiteflies": [
    "basil",
    "mint"
  ]
};

/** Every companion/remedy plant id referenced by the dataset. */
export const REMEDY_IDS: string[] = [
  "basil",
  "borage",
  "catnip",
  "chamomile",
  "chives",
  "dill",
  "garlic",
  "lavender",
  "marigold",
  "mint",
  "nasturtium",
  "radish",
  "rosemary",
  "sage",
  "tansy"
];
